# For more details, see https://docs.github.com/en/actions
name: Build ros2installlib-tis images

# Controls when the workflow will run
on: workflow_dispatch

defaults:
  run:
    shell: bash

# For more details, see https://github.com/docker/build-push-action
jobs:
  ros2installlib:
    name: Ros2installlib
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: ros2installlib
          platforms: linux/amd64
          push: true
          tags: qubo188612/ubuntu20.04:ros2installlib
          cache-from: type=registry,ref=qubo188612/ubuntu20.04:ros2installlib
          cache-to: type=inline
  
